# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
# excluding of main repository paths from Code climate
- "assets/javascripts/backbone.js"
- "assets/javascripts/jquery.min.js"
- "assets/javascripts/require.js"
- "assets/javascripts/underscore.js"
