define ['backbone','jquery','text!/templates/header.html','handlebars'] , (Backbone,$,headerHTML,Handlebars) ->
  View =   Backbone.View.extend (
    el : 'header',
    initialize:  ->
     this.loadCss('../../stylesheets/components/3dmodel/header.css')
     this.render()
    render: ->
     $(this.el).html(headerHTML);
    loadCss : (url) ->
      $("head").append("<link id='yournewcss' href='"+ url+ "' type='text/css' rel='stylesheet' />");
  )
  View

# ---
# generated by js2coffee 2.1.0
