define ['backbone','jquery','text!/templates/header.html','handlebars'] , (Backbone,$,headerHTML,Handlebars) ->
  View =   Backbone.View.extend (
    el : 'header',
    initialize:  ->
     this.render()
    render: ->
     $(this.el).html(headerHTML);
  )
  View
 
# ---
# generated by js2coffee 2.1.0
